mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('chi-sono/', views.chi_sono, name='chi_sono'),
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
 'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
        .filter(status=Post.Status.PUBLISHED)
 
class Post(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()
    photo = models.ImageField(blank=True)
    
    class Meta:
        ordering = ['-publish']
        indexes = [
        models.Index(fields=['-publish']),
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
            ]
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, slug=post, publish__year=year, publish__month=month, publish__day=day)
    tags = Post.tags.all()
    tag = post.tags.all()
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()
    
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts, 'tags': tags, 'tag': tag})

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tags = Post.tags.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination with 9 posts per page
    paginator = Paginator(post_list, 9)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
    # If page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
    # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag, 'tags': tags})

def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'fabioprof96@gmail.com', [cd['to']])
            sent = True
            # ... send email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html', {'post': post, 'form': form, 'comment': comment})

def chi_sono(request):
    return render(request, 'blog/post/chisono.html')

mysite/blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="{% static "css/blog.css" %}" rel="stylesheet">

    </head>
    <body class="container">
        <div class="header">
            <h1><a href="{% url 'blog:post_list' %}">My Blog</a></h1>
            <ul class="categories">
                {% for tag in tags %}
                    <li>
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="footer">
            <div class="section">
              <h2>My blog</h2>
              <p>
                This is my blog.
                <a href="{% url 'blog:chi_sono' %}">
                    Chi sono
                </a>
                I've <br>written {% total_posts %} posts so far.
              </p>
            </div>
            <div class="section">
              <h3>Latest posts</h3>
              {% show_latest_posts 3 %}
            </div>
            <div class="section">
              <h3>Most commented posts</h3>
              {% get_most_commented_posts as most_commented_posts %}
              <ul>
                {% for post in most_commented_posts %}
                  <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <div class="section">
              <h3>Contact and Social</h3>
              <!-- Contatti e link ai social -->
            </div>
          </footer>
          
    </body>
</html>

mysite/blog/templates/blog/post/chisono.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Chi sono{% endblock %}

{% block content %}
    <h2>Chi sono</h2>
    <p class="chi_sono">
        Ciao a tutti,<br><br>

Sono Fabio, un giovane appassionato di sport e sviluppo software. Ho conseguito una laurea in Scienze delle Attività Motorie e Sportive presso l'Università di Torino, dove ho sviluppato solide competenze nell'ambito del corpo umano e dell'attività fisica.<br><br>

Fin dai tempi delle superiori, ho scoperto una passione innata per la risoluzione di problemi complessi e l'affronto di sfide intellettuali. Ho ottenuto diversi riconoscimenti in concorsi di matematica e logica, dimostrando una particolare abilità nel trovare soluzioni innovative.<br><br>

Dopo la laurea, ho deciso di seguire la mia seconda passione: lo sviluppo software. Mi sono immerso nell'apprendimento di linguaggi di programmazione come Python, che offre una grande versatilità e potenza. Successivamente, mi sono concentrato sul framework Django, che mi ha permesso di sviluppare progetti significativi, come blog personali, social network, siti e-commerce e piattaforme di e-learning.<br><br>

La programmazione mi affascina per la sua componente logica e la sfida mentale che comporta. Mi gratifica risolvere problemi complessi e creare soluzioni efficaci. Ho approfondito anche il mondo dei database, acquisendo competenze con MySQL per integrare le mie conoscenze nel back-end.<br><br>

Sono un apprendista veloce e motivato, sempre pronto ad adattarmi a nuovi ambienti di lavoro e ad apprendere nuove tecnologie. Lavoro efficacemente sia in autonomia che in team, collaborando con colleghi provenienti da diversi background.<br><br>

Sono entusiasta all'idea di mettere a frutto le mie competenze logiche, la creatività e la dedizione nello sviluppo di soluzioni software innovative. La mia formazione multidisciplinare, combinata con la passione per la logica e la risoluzione dei problemi, mi consente di offrire un approccio unico nello sviluppo di applicazioni di successo.<br><br>

Sono consapevole che il percorso che ho intrapreso è diverso da quello tradizionale per diventare uno sviluppatore software, ma credo fermamente che la mia combinazione di competenze, la motivazione e il desiderio di apprendere in modo continuo mi rendano un candidato ideale per affrontare nuove sfide in questo campo.<br><br>

Sono pronto ad affrontare nuove sfide e a contribuire con le mie competenze e la mia dedizione al successo del vostro progetto. Vi invito a esplorare il mio portfolio online, dove potrete trovare i progetti che ho realizzato durante il mio percorso di studio e apprendimento.<br><br>

Grazie per l'attenzione dedicata e spero di poter collaborare con voi per realizzare soluzioni software innovative e di successo.<br><br>

A presto,<br>

Fabio
    </p>
    
{% endblock %}

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h3>{{ tag|join:", " }}</h3>
    <h1>{{ post.title }}</h1>
    <div class="post-details">
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        <p class="share">
            <a href="{% url 'blog:post_share' post.id %}">
                Share this post<br>by e-mail
            </a>
        </p>
    </div>
    {{ post.body|markdown }}


    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}

    {% include "blog/post/includes/comment_form.html" %}

    <h2><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>Similar posts</h2>

    <div class="grid-container" style="grid-template-columns: repeat(5, 1fr)">
        {% for post in similar_posts %}
            <div class="grid-item" style="padding: 5px">
                <h2>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>
                <p class="tags">
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                {{ post.body|markdown|truncatewords_html:30 }}
            </div>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}
    </div>

{% endblock %}

mysite/blog/templates/blog/post/includes/comment_form.html
{% load crispy_forms_tags %}

<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}

    

    {% if tag %}
        <h2>"{{ tag.name }}" category:</h2>
    {% endif %}
    <div class="grid-container">
        {% for post in posts %}
            <div class="grid-item">
                {% if post.photo %}
                <div class="grid-item-image">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}">
                </div>
                {% endif %}
                <h2>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>
                <p class="tags">
                    Tags:
                    {% for tag in post.tags.all %}
                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p class="date">
                    Published {{ post.publish }} by {{ post.author }}
                </p>
                {{ post.body|markdown|truncatewords_html:30 }}
            </div>
        {% endfor %}
    </div>
    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}.</span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>